export const Types = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_AT_CART: "REMOVE_AT_CART",

  FETCH_CART_PRODUCTS: "FETCH_CART_PRODUCTS",
  FETCH_CART_PRODUCTS_SUCCESS: "FETCH_CART_PRODUCTS_SUCCESS",
  FETCH_CART_PRODUCTS_FAILED: "FETCH_CART_PRODUCTS_FAILED",

  CLEAR_CART_PRODUCTS: "CLEAR_CART_PRODUCTS",
};
