export const Types = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "FETCH_PRODUCTS_FAILED",

  FETCH_PRODUCT: "FETCH_PRODUCT",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILED: "FETCH_PRODUCT_FAILED",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_AT_CART: "REMOVE_AT_CART",

  FETCH_CART_PRODUCTS: "FETCH_CART_PRODUCTS",
  FETCH_CART_PRODUCTS_SUCCESS: "FETCH_CART_PRODUCTS_SUCCESS",
  FETCH_CART_PRODUCTS_FAILED: "FETCH_CART_PRODUCTS_FAILED",

  CLEAR_CART_PRODUCTS: "CLEAR_CART_PRODUCTS",
  LOADE_CART_PRODUCTS: "LOADE_CART_PRODUCTS",
};
